theme = "gruvbox"

[editor]
line-number = "relative"
auto-format = false
color-modes = true

[editor.lsp]
display-messages = false

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
